version: '3.8'
services:
  signage-app:
    build: .
    ports:
      - "8080:5000"
    volumes:
      - ./pdf_output:/app/pdfs:Z
      - ./forms:/app/forms:Z
      - ./pdf_templates:/app/pdf_templates:Z
    restart: unless-stopped
